### ISSUE TITLE
自動修正注音符號聲符韻符位置

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#1]
傳統的注音輸入法，如微軟的注音、新注音，以及開源的新酷音等，都有注音符號防錯功能。什麼意思呢？概略解釋一下。

防錯功能即容許快速打字時，字的聲符與韻符前後錯置時的自動校正，但音調仍舊必須放在最後。此為注音輸入法之基本功能。

例如輸入的注音符號為：ㄛㄨˇㄚㄉˇㄗˋㄞㄊˋㄨㄎㄞˋ
會自動修正成：ㄨㄛˇㄉㄚˇㄗˋㄊㄞˋㄎㄨㄞˋ

範例影片 ibus-chewing 如連結：https://dl.dropboxusercontent.com/u/5259212/ibus-chewing-WrongZhuyinPrevention.webm

如此可以大幅提昇打字速度。

**Comment by epico** [comment]
对于 “標準注音鍵盤” 等键盘映射，应该可以支持此功能。

不知道其他输入法，对于26键的键盘映射，是如何处理的？
因为26键的一个键有可能对应两个键。

我回来查查代码，看看如何实现。
欢迎告知相关信息，谢谢。

**Comment by epico** [comment]
大千26鍵可能无法支持此功能。
另外，我想问一下，使用大千26鍵的用户多吗？

**Comment by zerng07** [comment]
大千的用戶很少見，許氏可能比大千多些，但兩者都還是少數。

**Comment by zerng07** [comment]
是指倚天 26 鍵或許氏鍵盤25鍵嗎？

許氏大概比倚天使用者還多，但這兩者都還是少數。

**Comment by epico** [comment]
谢谢告知相关信息，我会在写代码的时候看看26键的键盘映射能不能支持这个功能。
大千26鍵的代码是特殊处理，可能不支持此特性的。

**Comment by epico** [comment]
目前，26键的键盘映射不能支持这个功能，仅对于一一对应的键盘映射可以支持此功能。

Draft code landed on https://github.com/epico/libzhuyin .

If possible, please help test it with tests/storage/test_parser2, thanks.

**Comment by epico** [comment]
As libzhuyin 1.0.0 and ibus-libzhuyin 1.7.0 released, close issue.
