### ISSUE TITLE
候選字詞輸入模式 (尚未 Commit 字詞) 下的 Shift 鍵行為

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#10]
當還在中文的候選字詞輸入模式，也就是還在打注音，輸入法還有底線提示尚未 Commit 字詞出去的時候，若按下 Shift 按鍵則無反應。

此時的使用情境是使用者已完成中文選字，想切換至英文繼續輸入。
建議按下 Shift 時直接 Commit 候選區的字詞，然後切換至英文模式讓使用者繼續輸入，讓 Shift 鍵不必多按下 Enter 就能生效 (一般的使用者預期行為)。

**Comment by epico** [comment]
我试了一下 ibus-chewing, 好像按下 Shift 时，是用来输入中文标点符号的。

**Comment by zerng07** [comment]
ibus-chewing 是拿 shift 做組合鍵輸出標點沒錯，如逗點 shift+, 句點 shift+. 等等；不過單獨按下 shift 是切換至英文模式。

我晚點拍攝螢幕畫面讓你看一下。

**Comment by zerng07** [comment]
ibus-chewing 的英打有兩種，一種是純英打，即現在 ibus-libzhuyin 這種，要先按下 Shift 切換到英文直接純打英文；另一種是在中文模式下打英文，即尚未 commit 字詞就按下 Shift 鍵切換到英文成中英混打。

範例影片如連結 https://dl.dropboxusercontent.com/u/5259212/ibus-chewing-ChEnMixInput.webm

**Comment by epico** [comment]
非常感谢，让我想想如何实现。:-)

**Comment by epico** [comment]
在中文输入时，按下 Shift 键，将自动提交并切换到英文模式。

Draft fixes landed on https://github.com/epico/ibus-libzhuyin .

**Comment by epico** [comment]
As libzhuyin 1.0.2 and ibus-libzhuyin 1.7.3 are released, close issue.

Feel free to comment it, if the problem still exists.
