### ISSUE TITLE
開頭若打出聲調，後面輸入的注音無法被轉成文字

### ISSUE THREAD

**Issue by FreedomKnight** [libzhuyin/ibus-libzhuyin#11]
事實上，我是在打字時先輸入幾個空白，然後發現後面的注音符號不會變成文字
似乎前面的空白被當成聲調了
我猜應該是判斷注音拼音的時候，沒有忽略掉開頭的聲調
（新注音的行為是不理會開頭多打的注音符號，多打的就會把該聲調符號準備 commit）
注音的聲調應該是只會出現在注音符號之後，所以只要判斷注音符號後面的一個聲調即可

可能要做些處理讓 ibus-libzhuyin 忽略掉開頭可能打出的聲調符號

**Comment by zerng07** [comment]
實際結果：
水果ˇㄕㄨㄟˇㄍㄨㄛˇ
ˇㄕㄨㄟˇㄍㄨㄛˇ

預期結果：
水果ˇ水果
ˇ水果

**Comment by zerng07** [comment]
另外以空白來測試，

實際結果：
水果 ㄕㄨㄟˇㄍㄨㄛˇ
 ㄕㄨㄟˇㄍㄨㄛˇ

預期結果：
水果 水果
 水果

**Comment by FreedomKnight** [comment]
該狀況不是說使用者刻意使用彆扭的輸入方式
主要會需要忽略的情況是如下：
實際結果：
好的 ㄨㄛˇㄏㄨㄟˋㄕˋㄕˋ

預期結果：
好的 我會試試

主要是中間那個空白是打字時需要的，但因為多輸入個空白，就一定要先 commit 一次，才能繼續打下一段文字

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/ibus-libzhuyin/ .

If possible, please help test it, thanks.

**Comment by FreedomKnight** [comment]
目前測試了一下，似乎沒有太大的問題。
最近我會穩定使用，如果有什麼大問題，我會持續回報的，非常感謝您

**Comment by zerng07** [comment]
太棒了！

**Comment by epico** [comment]
New fixes landed on https://github.com/epico/ibus-libzhuyin/ .

**Comment by zerng07** [comment]
Tested. 使用上沒甚麼問題。

**Comment by epico** [comment]
As libzhuyin 1.0.2 and ibus-libzhuyin 1.7.3 are released, close issue.

Feel free to comment it, if the problem still exists.
