### ISSUE TITLE
按 esc 無法關閉候選視窗

### ISSUE THREAD

**Issue by FreedomKnight** [libzhuyin/ibus-libzhuyin#12]
目前按方向鍵「下」開始選字之後，再按 esc 會無法關閉候選字的視窗

**Comment by epico** [comment]
Draft fix landed on https://github.com/epico/ibus-libzhuyin .

**Comment by epico** [comment]
As libzhuyin 1.0.2 and ibus-libzhuyin 1.7.3 are released, close issue.

Feel free to comment it, if the problem still exists.
