### ISSUE TITLE
將 usersymbol.txt 加入《重訂標點符號手冊》修訂版內的標點符號

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#13]
目前 usersymbol.txt 裡面缺失一些規範中的標點符號。[1]

我將之加入爲「標點符號」，並稍微調整刪除了其他重複項目，diff 了一個 patch。[2]

1. http://www.edu.tw/FILES/SITE_CONTENT/M0001/HAU/haushou.htm#suo
2. https://www.dropbox.com/s/uz37hyw3rzh7lf0/add-standard-symbols.patch?dl=0

**Comment by epico** [comment]
方便的话，请创建一个 Pull Request, 感谢您的贡献。 :-)

**Comment by zerng07** [comment]
OK, 我晚點弄。

**Comment by zerng07** [comment]
剛剛試了一下，似乎要把現在的 PR 處理完才能新建另一個 PR，介面沒地方按 Create pull request。:P

**Comment by epico** [comment]
Patch merged, thanks. :-)
