### ISSUE TITLE
候選字詞聲調不分

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#15]
目前 ibus-libzhuyin 的操作上已無太大問題，我已開始日常使用作測試。現在發現有一個輸入法本身的主要問題，就是輸入法給的候選字詞是同音但不分聲調的。

例如打ㄐㄧㄣˋㄑㄩˇ (進取) 會跳出「金曲」(ㄐㄧㄣ ㄑㄩˇ)，這是不符合注音使用者預期的。
單一個字也是如此，例如打ㄓㄨˋ (注) 會跳出「朱」(ㄓㄨ )，而候選字選單裡有ㄓㄨˋ (住) 也有ㄓㄨ (諸)，混雜在一起；但奇怪的是卻不見ㄓㄨˇ(主)。
還有打ㄒㄧㄤˇ會出現「鄉」(ㄒㄧㄤ )…等。

從目前輸入法的行為來看，還滿常見候選字詞不分聲調的。但這是注音輸入法使用者無法理解的行為，畢竟已經輸入聲調，應當過濾到只剩相同聲調的字詞 (不管是 Windows 的注音與新注音、Linux 的 ibus-chewing、Mac、iOS、Android 等注音類輸入法皆是如此)；一開始使用者會以爲是自己打錯，但若發現是輸入法行為時，根據其既有使用經驗來看就會認為是設計失誤。

想請問原因是否跟詞庫 (即字與注音之對照表) 有關？如果是詞庫問題，建議可以直接改用新酷音的詞庫。
如果與詞庫無關，是否有機會改善呢？

**Comment by epico** [comment]
实际上， libzhuyin 用的是 libchewing 的词典。
不知道能否帮看一下，libzhuyin/data/tsi.table 和 libchewing/data/tsi.src 是否有问题。
如果没问题的话，我再看看是不是代码的问题，谢谢。

**Comment by epico** [comment]
稍微挑选几个有问题的注音，比较一下即可，谢谢。
不好意思，我还看不太懂注音符号...

**Comment by epico** [comment]
刚刚打印了个注音键盘，这个问题我下周看一下。

**Comment by zerng07** [comment]
感謝你！

抱歉我還不大懂程序設計… 可能得好好來學一學了！

**Comment by epico** [comment]
请教个问题，在注音规范中，是不是平声（"ˉ"）默认是不标注的？

**Comment by zerng07** [comment]
是的，平聲默認不標注。

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/libzhuyin .

**Comment by zerng07** [comment]
測試了一下，陰平 (一聲，以「 」空白表示) 似乎沒有問題。

不過陽平 (二聲，以「ˊ」表示) 與上聲 (三聲，以「ˇ」表示) 看起來問題還在。
以ㄗㄨ (zu 租) 為例，
一聲陰平的ㄗㄨ，候選字有租、蒩；
二聲陽平的ㄗㄨˊ，除了族、足、卒…等二聲ㄗㄨˊ外，依然有租、蒩二字。
三聲上聲的ㄗㄨˇ，除了組、祖、阻…等三聲ㄗㄨˇ外，依然有租、蒩二字。
四聲去聲的ㄗㄨˋ，除了駔、錊外，依然有租、蒩二字。

另外試驗了ㄓㄨ(zhu 朱)，也是一樣，一聲的朱、諸、豬…等字，都重複出現在二聲、三聲、四聲的候選字選單中。

**Comment by zerng07** [comment]
等等，我好像編譯錯了，正在請教 freedomknight 中。

**Comment by zerng07** [comment]
抱歉，我看錯 repo，編譯到 https://github.com/epico/ibus-libpinyin 去了，正在重新編譯中。

**Comment by FreedomKnight** [comment]
我這邊是可以正常顯示，但是似乎 esc 取消選字又壞了

**Comment by zerng07** [comment]
經過測試 (重編 libzhuyin 與 ibus-libzhuyin)，已無我剛剛所述的二三四聲調選字重複問題！！！目前使用正常，也沒有 ESC 取消選字的問題，FreedomKnight 要檢查看看嗎？

不過我對於空白鍵還有個建議，就是中打模式下面，單打空白鍵，也就是空白鍵放在任意注音符號前方的情況建議直接輸出。一個使用案例就是想要直接按空白鍵插入字跟字之間排版，以目前的行為來看，使用者需要多按下一次 Enter 才能生效。直覺上，應該單打空白時會直接視為空白，只有在注音符號後方的第一個空白才是一聲的陰平聲調。

**Comment by epico** [comment]
关于空白键的建议，方便的话，请开新的 issue 讨论。 :-)

**Comment by epico** [comment]
As libzhuyin 1.0.2 and ibus-libzhuyin 1.7.3 are released, close issue.

Feel free to comment it, if the problem still exists.
