### ISSUE TITLE
獨立空白鍵直接輸出

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#16]
對於空白鍵還有個建議，就是中打模式下面，單打空白鍵，也就是空白鍵放在任意注音符號前方的情況建議直接輸出。

一個使用案例就是想要直接按空白鍵插入字跟字之間排版，以目前的行為來看，使用者需要多按下一次 Enter 才能生效。直覺上，應該單打空白時會直接視為空白，只有在注音符號後方的第一個空白才是一聲的陰平聲調。

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/libzhuyin and https://github.com/epico/ibus-libzhuyin .

**Comment by zerng07** [comment]
測試了一下，目前變成按了空白就直接輸出。這在單純在已打好字詞之間補入空白是對的行為。

不過，打「ㄘㄜˋㄕˋ(空白)ㄘㄜˋㄕˋ」，當一按到空白鍵時就會自動輸出前方的第一個測試，僅留下後方的測試在候選區中。但這裡的中央空白只是單純排版用途，所以使用者會預期尚未輸出第一個詞語，會等一併輸入完再來選 (注音輸入法類的使用習慣)。這我當初沒有想到有這樣的使用案例…

在來測試兩字詞間置入聲調符號，如「ㄘㄜˋㄕˋˋㄘㄜˋㄕˋ」，會輸出爲「測試ˋㄘㄜˋㄕˋ」，即 Issue #11 的問題又再次發生。

**Comment by epico** [comment]
请问我可以取消这个修正吗？ 毕竟这和 ibus-chewing 的行为不一致。
我会试试重新修正 Issue #11 .

**Comment by zerng07** [comment]
可以啊，還麻煩你了！

**Comment by epico** [comment]
好的，此更改已取消。

**Comment by mingtsay** [comment]
在 Windows 以及 Mac OS X 上的習慣為，無任何文字時按下空白鍵將直接輸出空白，有文字正在候選時會打開候選清單列表，也就是 @zerng07 所說的按下空白直接輸出，這確實跟 ibus-chewing 的行為不一致。

**Comment by epico** [comment]
ibus-libzhuyin 当前仅支持一种输入行为，如果要支持多种输入行为，欢迎 fork ibus-libzhuyin.

谢谢。:-)

**Comment by epico** [comment]
As libzhuyin 1.0.2 and ibus-libzhuyin 1.7.3 are released, close issue.

Feel free to comment it, if the problem still exists.

**Comment by zerng07** [comment]
這個 Issue 還沒有在 1.7.3 中得到解決。

獨立空白鍵直接輸出是目前所有注音類輸入法的基本使用習慣，不管是非智慧型的 ibus-zhuyin 或微軟注音，或是智慧型的 ibus-chewing 或微軟新注音，皆可以直接輸出獨立空白不必再 Enter 的。

**Comment by epico** [comment]
不好意思，理解错了...

就是说应该在没有候选输入的时候，按空格键直接输出空格？是要改成这样吗？

**Comment by zerng07** [comment]
是的。

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/ibus-libzhuyin .

And "Use Space Key to Show Candidates" option is added.

**Comment by zerng07** [comment]
測試結果：

若勾選 "Use Space Key to Show Candidates" 選項，則無法使用空白鍵作為一聲 (輕聲) 聲符。
如：風，注音符號爲 "ㄈㄥ "，按鍵對應爲 "z/ "，結尾字符是空白鍵，則無法輸出漢字。
其餘聲符運作正常。

最後，直接輸出空格的功能，不管是否勾選 "Use Space Key to Show Candidates" 選項也都能作用正常。確認已修正。

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/ibus-libzhuyin .

**Comment by zerng07** [comment]
經測試確認上述空白鍵問題已修正！

**Comment by kidwm** [comment]
@zerng07 那可以結案了？

**Comment by epico** [comment]
okay, close issue.
