### ISSUE TITLE
候選字選擇方式游標位置設定

### ISSUE THREAD

**Issue by mingtsay** [libzhuyin/ibus-libzhuyin#17]
例如：我正在用注音輸入文字

在 Windows 的習慣，如果我選字要針對「注音」選字的時候，需將游標移動至「注」前方，如：「我正在打 | 注音輸入」
在 Mac OS X 的習慣，則是將游標移動至「音」後方，如：「我正在打注音 | 輸入」

請問是否能提供該選項於偏好設定供使用者選擇？
謝謝！

**Comment by epico** [comment]
这个好像很难，因为 m_cursor 被用在了很多地方。

**Comment by epico** [comment]
有需要的话，欢迎 fork ibus-libzhuyin. :-)

**Comment by zerng07** [comment]
基本上 windows 平臺上的微軟注音、微軟新注音、新酷音等，都是默認游標移動到字詞前方選詞的 (不過新酷音可以改設定爲後方選詞)。

目前僅有 ibus-chewing 採取預設游標移動到字詞後方改詞。

**Comment by epico** [comment]
好的，我看看代码，看看应该如何修改。 :-)

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/libzhuyin and https://github.com/epico/ibus-libzhuyin .

Option "Show Candidates After the  Cursor" added.

**Comment by zerng07** [comment]
經簡單輸入測試成功，確認已修正。

**Comment by kidwm** [comment]
@epico so is it okay to close issue?

**Comment by epico** [comment]
okay, close issue.
