### ISSUE TITLE
若輕聲的「˙」聲調符號無法構成字則 ibus-libzhuyin 將無法反應

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#18]
目前遇到一個輸入問題，就是當使用者誤按鍵盤輕聲的「˙」(按鍵 7) 時，若該註音符號無法輸出候選字 (無可以對應的字)，如「ㄆㄨ˙」，則 ibus-libzhuyin 的中文模式將失去反應無法再處理任何輸入。

此時若按下 Shift 先切換到英文模式，再按 Shift 切換回中文模式後 (即按 Shift 兩下) 就能恢復輸入。

重現方法：
1. 輸入「ㄆㄨ˙」(鍵盤對應爲 qj7)
2. 嘗試輸入其他任何字詞，可以發現 ibus-libzhuyin 失效

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/libzhuyin and https://github.com/epico/ibus-libzhuyin .

**Comment by zerng07** [comment]
經測試確認已修正。

**Comment by kidwm** [comment]
@zerng07 那怎麼沒人 close issue?

**Comment by epico** [comment]
之前是 tar ball 发布后，close issue.

也可以早点 close issue. :-)
