### ISSUE TITLE
候選字詞出現後 Delete 一鍵可刪除一字

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#2]
以往的智慧型注音輸入法，若已有候選字詞出現時，Delete 鍵可以一次刪除一字，而非一個符號。
例如輸入：ㄓˋㄏㄨㄟˋ 後，會自動出現候選詞「智慧」，此時若按下 Delete 鍵可以刪除「慧」，剩下的「ㄓˋ」會因為刪除後方的「ㄏㄨㄟˋ」而隨之重新選擇候選字。

以 ibus-chewing 為例之影片：https://dl.dropboxusercontent.com/u/5259212/ibus-chewing-DeleteKey-Candidate.webm

此 Delete 鍵之使用方式為智慧型注音輸入法之傳統，若能與之相同即能無痛轉移使用 ibus-libzhuyin。

**Comment by epico** [comment]
Draft patch landed on https://github.com/epico/ibus-libzhuyin.

**Comment by epico** [comment]
As libzhuyin 1.0.0 and ibus-libzhuyin 1.7.0 released, close issue.
