### ISSUE TITLE
候選字詞尚未輸出時，若游標向前移動補輸入字，將使最後一個字的候選消失

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#20]
重現方式如下：
1. 輸入「hk4g4」(即「ㄘㄜˋㄕˋ」)，此時候選字詞會變成「測試」，游標位於「試」的後方
2. 按下「左方向鍵」讓游標往前移動一個字，游標位於「測」的後方
3. 輸入「2u03」(即「ㄉㄧㄢˇ」，音同點)，此時候選字詞會變成「冊點ㄕˋ」，使最後一個字的候選消失

最後一個字的候選消失後，就會維持注音符號不變，無法再轉換成漢字了。

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/ibus-libzhuyin .

**Comment by zerng07** [comment]
經測試已能正常使用。

感謝！！！:)
