### ISSUE TITLE
candidate 游標前選詞或游標後選詞若遇上標點符號會有問題

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#21]
一、若勾選 Show Candidates After the Cursor 會有以下選字問題
重現步驟：
1. 輸入「'hk4」即「、測」，還不要按下 Enter 提交字詞
2. 按下「左鍵」移動游標到「測」前方，按下「下鍵」
3. 使用者預期的是「測」字的候選字詞選單，但結果顯現的是標點符號「、」的候選字詞選單，無從改變「測」字的候選字詞

二、若不勾選 Show Candidates After the Cursor 會有以下選字問題
1. 輸入「hk4'g4」即「測、是」，還不要按下 Enter 提交字詞
2. 按下「左鍵」兩下，移動游標到「測」後方，按下「下鍵」，「測」字的候選字詞選單正常顯示
3. 離開候選字詞選單，接著假定使用者想要修改「是」字，按下「右鍵」兩次
4. 結果游標停在「是」前方，須要再按下「右鍵」一次才能到「是」的後方 (註：3、4 之處即為有問題的地方)
5. 「是」字的候選字選單正常顯示

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/ibus-libzhuyin .

**Comment by epico** [comment]
As ibus-libzhuyin 1.7.5 is released, close issue.
