### ISSUE TITLE
依然是標點與游標之間的問題

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#23]
今天 fedora 推送 1.7.5 版，方才順帶測試了一下標點問題。

#21 修正了選詞的問題，但引發了新的問題會導致 ibus-libzhuyin crash。重現方式如下：

1. 輸入「hk4'」(測、) 後，游標向左移動再向右移動 (即移動到標點、前再移回來)。
2. ibus-libzhuyin crash

不管偏好設定中 Show Candidates After the Cursor 有無勾選都一樣。

以上回報。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/e94fe7e9209ce7bc53afb8095ea27a36d3293616 .

**Comment by epico** [comment]
刚刚更新了 Fedora 的包。 :)

Refer URL:
https://bodhi.fedoraproject.org/users/pwu

**Comment by zerng07** [comment]
經過簡單測試，如果在標點前後移動，還是有一點小問題。

重現方式：
1. 若勾選 Show Candidates After the Cursor
2. 輸入「hk4'g4」(測、是) 後，游標向左移動，並試圖在、頓號前後移動。會發現向左返回、頓號前方後，若再前進到、頓號後方，此時試圖再返回、頓號前方會發現游標移動失敗，要再多按一次才能正常移動游標。

1. 若不勾選 Show Candidates After the Cursor
2. 輸入「hk4'g4」(測、是) 後，游標向左移動，並試圖在、頓號前後移動。會發現先向左返回、頓號前方，再前進到、頓號後方 (這時按下鍵打開候選詞列表時會發現空白列表)，此時若試圖再返回、頓號前方會發現游標移動失敗  (這時按下鍵打開候選詞列表時可正常顯示列表)，要再多按一次才能正常移動游標。

**Comment by epico** [comment]
Draft fix landed on https://github.com/epico/ibus-libzhuyin/commit/63ed6f0427742a0e6f50195aeca84380191b7bfb .

**Comment by zerng07** [comment]
測試成功，確認沒問題～ 感謝！！！:)

**Comment by epico** [comment]
不好意思，刚刚做了些代码清理工作，能帮忙测试一下吗？

没问题的话，将会发布 ibus-libzhuyin 1.7.6.

新的代码在 https://github.com/epico/ibus-libzhuyin , 谢谢。:-)

**Comment by zerng07** [comment]
稍微測試了一下，感覺很好還沒遇到問題！

**Comment by epico** [comment]
谢谢!

ibus-libzhuyin 1.7.6 已发布，关闭 issue. :)
