### ISSUE TITLE
全形字母模式下無法輸入全形大寫字母

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#26]
重現方式：
1. 按下 shift 切換到英文
2. 點右上角輸入法選單中的「半形字母」切換成全形字母（等等，我怎麼覺得這個設計怪怪的？或許該弄成點按全形字母按鈕下拉出現開或關，但先不管，這不是本 bug 重點）
3. 按下 shift A 試圖輸出大寫的全形字母 A，但卻是正常的半形字母；若是直接按下 A B C 可以看到預期的全形 ａｂｃ。

**Comment by Vdragon** [comment]
←苦主
我的暱稱是「Ｖ字龍」，但是我連第一個字都打不出來

**Comment by Vdragon** [comment]
是說 ibus-chewing 也有這個問題，應該是 ibus 本身的 bug？

**Comment by lantw44** [comment]
我剛才在 ibus-chewing 1.5.0 測試沒有遇到問題耶

**Comment by epico** [comment]
不好意思，是个 bug.

在 https://github.com/epico/ibus-libzhuyin/commit/e8c56047983b3c8562598f8fcdf62ced95fdbb0c 中， 已修正。
方便的话，帮忙测一下，谢谢！

**Comment by Vdragon** [comment]
@lantw44 現在沒在用 ibus-chewing，有可能是我記錯了

**Comment by epico** [comment]
As ibus-libzhuyin 1.7.7 is released, close issue.

**Comment by Vdragon** [comment]
嗨！最近安裝了 Fedora 24（搭載了 ibus-libzhuyin 1.7.7），但是還是遇到相同的問題（按下 shift A 試圖輸出大寫的全形字母 A，但卻是正常的半形字母；若是直接按下 A B C 可以看到預期的全形 ａｂｃ）

**Comment by epico** [comment]
也许需要先将 "全角字母" 的开关打开...

**Comment by Vdragon** [comment]
@epico > 也许需要先将 "全角字母" 的开关打开...

我打開了，行為相同

**Comment by epico** [comment]
我这里测试，已经修复了啊。

**Comment by Vdragon** [comment]
@epico 重開機之後又突然好了orz，不知道是不是因為我把「英語（美國）」輸入來源移除只留下「新注音」輸入來源的緣故，先關閉 issue 吧

**Comment by zerng07** [comment]
我 f24 機上測試也是已修復狀態。

**Comment by epico** [comment]
好的，关闭 issue.
