### ISSUE TITLE
支援以 Shift+Space 組合鍵切換字母全 / 半形狀態

### ISSUE THREAD

**Issue by Vdragon** [libzhuyin/ibus-libzhuyin#27]
如題，這是微軟新注音 / HIME(gcin) 輸入法的預設值，希望新注音也能支援。

**Comment by zerng07** [comment]
支持。
ibus-chewing 也是沿襲用 Shift+Space 組合鍵交互切換字母全/半形狀態的慣例。

**Comment by epico** [comment]
Draft fixes in https://github.com/epico/ibus-libzhuyin/commit/97f89f6f939d86da27565897d82e8fafff7298cb .

**Comment by epico** [comment]
As libzhuyin 1.1.1 and ibus-libzhuyin 1.7.8 are released, close issue.
