### ISSUE TITLE
在英文模式下無法輸入全形符號

### ISSUE THREAD

**Issue by Vdragon** [libzhuyin/ibus-libzhuyin#28]
在英文模式下「全形符號」的開關是停用的無法切換，在我的情況中我想輸入全形的「正斜線(/)」。

**Comment by Vdragon** [comment]
跟 #29 相關。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/6a2db8748b9ab84ae1d0ae9e60589a9051f2a27a .

**Comment by epico** [comment]
As libzhuyin 1.1.1 and ibus-libzhuyin 1.7.8 are released, close issue.
