### ISSUE TITLE
將全 / 半形字母跟符號分開的必要性？

### ISSUE THREAD

**Issue by Vdragon** [libzhuyin/ibus-libzhuyin#29]
有必要把字母跟符號分開嗎？我只有在新注音看到這個行為

**Comment by epico** [comment]
这个特性是从ibus-libpinyin 继承过来的...

**Comment by epico** [comment]
也许应该做个小调查...

**Comment by epico** [comment]
@zerng07 你认为这个建议怎么样？

如果其他 Zhuyin 输入法都只有一个选项的话，我将合并 ibus-libzhuyin 的这两个选项。

**Comment by zerng07** [comment]
全半形的存在，最早是為了適應排版用的；區不區分開來只是給使用者方便選擇。
目前 ibus-chewing、微軟新注音都只有一個選項，同時切換字母和符號的全半形。

建議可以依循注音使用者習慣，只用一個選項。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/compare/97f89f6f93...0b307f1eb7 .

**Comment by epico** [comment]
As libzhuyin 1.1.1 and ibus-libzhuyin 1.7.8 are released, close issue.
