### ISSUE TITLE
手動選字後卻又自動選字錯誤的問題

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#30]
描述情境如下：
1. 剛才試圖輸入「日本語彙」，這是一本書名，輸入法輸出前的緩衝區為「日本語會」，個人只想修改「會」為「彙」。
2. 手動將「日本語會」試圖調整成「日本語彙」後，又觸發輸入法自動選字為「日本與彙」
3. 只好再次手動調整「與」成「語」

現象：
之所以手動修改「會」字，是因為「語彙」是個詞，只差一個字正確。

問題點：
不知道再次觸動自動選字的原因為何？是因為改變了輸入法推測的斷字點所以重新智慧選字嗎？如果是的話，是不是該抑制輸入法這種聰明反被聰明誤的手動選字後的輸入法智慧選字？

**Comment by epico** [comment]
我想说这是一个 feature, 在多数情况下，自动修正应该是有帮助的...

**Comment by epico** [comment]
也许可以移动光标到 "日本|語彙"，然后选择候选词 "語彙"。

**Comment by zerng07** [comment]
但直觀上用戶只看到錯字「會」，因此不會特別想到可以藉由選擇「語彙」這個候選詞來修正「會」。

目前還想不到「在使用者手動修改後再次自動選字」有任何好處。看看其他人還有沒有相關意見的，不然我還是覺得應該抑制這種「自作聰明」。

**Comment by FreedomKnight** [comment]
或許可以在選擇 "會" 的時候讓鄰近一個字加入單詞候選讓人可以選到 "語彙" 這個詞?

**Comment by epico** [comment]
在输入姓名或出现多个错字的时候，会有帮助...

另外，在这个例子中，用户修正两个字之后，下次输入法就会记住这个句子，不需要再次更正。

这个特性也许需要用户适应一下，我暂时不想关闭这个功能...

**Comment by zerng07** [comment]
瞭解。

那先 close，以後有需要再 reopen。

**Comment by epico** [comment]
好的。 :)
