### ISSUE TITLE
1.7.8 下 Shift + 標點無法正確輸出預期的全形標點

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#31]
version: 1.7.8

預設中文輸入模式下（中文、半形），Shift + 標點符號預期應該仍是全形符號。可能先前修正的部份導入了新問題，非常抱歉我先前沒時間做測試。:P
　
重現方式:
1. Shift + , 或 . 預期「，」或「。」目前 regression 成「>」
2. Shift + [ 或 ] 預期『「』或『」』，目前 regression 成 {}

諸如此類。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/86159783e0ab330bdeff3d1dc21d2479485c7ae6 .

**Comment by zerng07** [comment]
新修正後的問題：
中文、半形模式下，有些常用標點如「、」原先便不需 Shift modifier，所以「'」預期的是直接輸出全形「、」，而修正後變為「'」；「[」「]」預期的是全形『「』、『」』，經此修正後為「[」、「]」。 

英文、全形模式下，Shfit + , 或 . 預期是全形的「＜」或「＞」，此修正後為「，」或「。」；而 [] {} 預期的是〔〕和｛｝，此修正後為「」『』。

**Comment by epico** [comment]
不好意思，我对 libchewing 的符号处理机制理解错了，已修正。

Fixed in https://github.com/epico/ibus-libzhuyin/compare/d8022f8fed9a81475f8aceca2fbb90292ace8284...252e606d4f0551b33eb3b30ac596a913b5e4793c .

**Comment by zerng07** [comment]
目前測試沒有問題了！感謝！

**Comment by epico** [comment]
As ibus-libzhuyin 1.7.9 is released, close issue.

**Comment by zerng07** [comment]
抱歉，最近日常使用後，發現英文、半形模式下，原本應該是半形的空白、逗號、句號… 都是全形。
重現方式：
1. 切換到 ibus-libzhuyin
2. 按下 shift 切換到英文模式，此時預期是正常英文輸入（英文、半形）。
3. 輸入「I have an apple.」會變成「I　have　an　apple。」

抱歉上次測試時沒有注意到「英文半形」模式下的問題。
