### ISSUE TITLE
Shift+空白鍵作全形、半形標點切換時不需輸出空白

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#32]
重現方式：
1. 進入 ibus-libzhuyin 輸入法，預設輸入狀態為中文、半形
2. 按下 Shift+空白 從半形切換成全形
3. 發現輸入法輸出半形空白 (但沒有必要)
4. 按下 Shift+空白 從全形切換成半形
3. 發現輸入法輸出全形空白 (但沒有必要)

以上回報！

**Comment by zerng07** [comment]
fixed confirmed.

**Comment by zerng07** [comment]
抱歉，我應該等 push 到這邊的 repo 再關閉的… 一時沒想清楚。:P

**Comment by epico** [comment]
没关系，可以关闭此 issue 的。
