### ISSUE TITLE
英文、半形模式下，應是半形的空白、逗號、句號等都輸出為全形

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#33]
英文、半形模式下，原本應該是半形的空白、逗號、句號… 都輸出為全形。

版本：1.7.9

重現方式：
1. 切換到 ibus-libzhuyin
2. 按下 shift 切換到英文模式，此時預期是正常英文輸入（英文、半形）。
3. 輸入「I have an apple.」會變成「I　have　an　apple。」

至於中文、半形正常，中文、全形正常，英文、全形也正常。

抱歉上次測試時沒有注意到「英文半形」模式下的問題。issue #31

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/805436ee90b1fe817e119c22462db4f89c34bc67 .

Please review it, thanks!

**Comment by zerng07** [comment]
測試：
一、中文、半形，正常：測試，測試、再測試。
二、英文、半形，正常：abc def, ghi.;:?!
三、中文、全形，不正常：測試＜測試’再測試＞
四、英文、全形，正常：ａｂｃ　ｄｅｆ，ｇｈｉ。；：？！

中文、全形下，預期全形標點如 Shift+, 的「，」和 ' 的「、」在此修正中為「＜」和「’」。

此外，原先中文、半形下， [ ] 兩鍵輸入後的候選符號，原先可以利用上下鍵開啟候選單，目前無法；只有中文、全形下的上下鍵可以正常叫出候選單。

**Comment by epico** [comment]
Thanks very much for the report!

Fixed in https://github.com/epico/ibus-libzhuyin/compare/805436ee90b1fe817e119c22462db4f89c34bc67...85a231f5999a7da1f9516934f70ca6bd5c68f52c .

**Comment by zerng07** [comment]
感謝！

目前經測試一切正常！我想全半形這個部分應該正式解決了！:)
