### ISSUE TITLE
Cannot build ibus-libzhuyin 1.8.0 in Debian

### ISSUE THREAD

**Issue by czchen** [libzhuyin/ibus-libzhuyin#37]
Currently I am working on pack ibus-libzhuyin 1.8.0 (with [libpinyin 2.1.0](https://tracker.debian.org/pkg/libpinyin)) into Debian. However, I got the following error when building it. Please help to check what's wrong.

```
make[3]: Leaving directory '/home/czchen/src/debian/ibus-libzhuyin/data/icons'
Making all in model
make[3]: Entering directory '/home/czchen/src/debian/ibus-libzhuyin/data/model'
rm -f phrase_index.bin pinyin_index.bin addon_phrase_index.bin addon_pinyin_index.bin bigram.db tsi.bin
gen_binary_files --table-dir ../../data/model
gen_binary_files: table_info.cpp:211: bool pinyin::SystemTableInfo2::load(const char*): Assertion `PINYIN_TABLE == type' failed.
Makefile:579: recipe for target 'bigram.db' failed
make[3]: *** [bigram.db] Aborted
```

**Comment by epico** [comment]
From the log, it seems to use old version of /usr/bin/gen_binary_files from libpinyin
project.

It needs to update /usr/bin/gen_binary_files to libpinyin 2.1.0.

**Comment by czchen** [comment]
Thanks for the hint. I forgot to set proper version constraint in Build-Depends.

**Comment by epico** [comment]
Welcome! :)
