### ISSUE TITLE
Ctl+Enter 在中文模式下沒有作用

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#38]
例如在 LibreOffice 中，Shift+Enter 用來中斷並跳至新行，Ctrl+Enter 則是中斷並跳至新頁。

ibus-libzhuyin 1.71.0 中，中文模式下 Shift+Enter 在 LibreOffice 中能作用，但 Ctrl+Enter 則無法；英文模式下兩者皆正常作用。問題可持續重現。

預期行為是 Ctrl+Enter 在中文模式下也能作用。

**Comment by epico** [comment]
Fixed in https://github.com/libzhuyin/ibus-libzhuyin/commit/ff9ea6940d6f5182c2213930893f726aa87c48ec .

Please try it, thanks!

**Comment by epico** [comment]
as ibus-libzhuyin 1.8.1 is released, close issue.
