### ISSUE TITLE
輸入法代表字符建議用ㄅ代替ㄉ

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#4]
Windows 平臺上的注音輸入法皆以第一個注音符號，即ㄅ字符代表注音輸入法。

建議採用ㄅ取代現在使用之ㄉ，以協助使用者迅速轉移、上手。

**Comment by epico** [comment]
不好意思，最近在忙别的项目，过一阵儿我看看。

**Comment by zerng07** [comment]
瞭解。

謝謝！

**Comment by epico** [comment]
我查看了下 新酷音和中州韻 输入法，发现他们用的是自己的图标。

请问是哪个注音輸入法用的 “ㄅ”？

**Comment by epico** [comment]
“ㄉ” 好像是用的频率最高的注音符号。
我对注音不太熟悉，如有错误，欢迎指出。

**Comment by zerng07** [comment]
微軟平臺下有兩種注音輸入法，一種是笨蛋型 (即候選字順序固定不受訓練改動，且不會自動判斷可能的詞)，一種是智慧型。笨蛋型的浮動列顯示「ㄅ」「半」兩個按鈕，ㄅ按下會切換成「英」，「半」按下去會切換成「全」，就是中英切換與全形半形切換，臺灣人稱之為「ㄅ半」輸入法。至於智慧型的注音輸入法則直接稱微軟採用的名稱，即「新注音」輸入法。這兩者皆已ㄅ為字符，注音的底圖是灰色；新注音的底圖是彩色。

由於臺灣的資訊教育都建構在微軟平臺上，因此幾乎第一個接觸的注音輸入法都是採用「ㄅ」，用ㄅ較符合使用習慣。

另一個原因是，例如英文多用第一個字母 A 表示，日文多用五十音第一個字符 あ 表示，順著這個邏輯下來，注音可用ㄅ表示。

**Comment by epico** [comment]
不好意思，我刚刚查看的 Windows 版本太老了，这个问题我尽快修正。
非常感谢提供相关信息。:-)

**Comment by epico** [comment]
Changes landed on https://github.com/epico/ibus-libzhuyin/.

Feel free to comment it.

**Comment by epico** [comment]
As libzhuyin 1.0.0 and ibus-libzhuyin 1.7.0 released, close issue.
