### ISSUE TITLE
無法輸入數字

### ISSUE THREAD

**Issue by cbf16888** [libzhuyin/ibus-libzhuyin#41]
於ibus-new zhuyin使用時鍵盤右邊九宮格數字鍵無法打出數字
使用方式:於Fedora設定中->地區及語言選項->新增->漢語(臺灣)->漢語(New Zhuyin)
輸入文字時切換到"漢語(New Zhuyin)"時且輸入模式為中文輸入模式時 鍵盤右邊的九宮格無法輸入數字
只有英文模式時能輸入數字
預期行為為中文模式時鍵盤右邊九宮格仍可輸入數字

**Comment by epico** [comment]
在首选项对话框里，有选项 "小鍵盤始終輸入數字", 看看打开后是否生效？

**Comment by cbf16888** [comment]
沒有效果

**Comment by epico** [comment]
这个问题我回来看一下。

在修复之前，关闭 Num Lock, 好像能输入数字。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/6b5e9e1987117a72da66a04012de8d5e580cc513 .

Please try it, thanks!

**Comment by epico** [comment]
as ibus-libzhuyin 1.8.1 is released, close issue.
