### ISSUE TITLE
ibus-libzhuyin 1.8.1 候選字詞未預期行為

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#42]
ibus-libzhuyin 1.8.1 on fedora 27

重現步驟：
1. 輸入任何字詞，如ㄘㄜˋ（hk4），候選為「冊」
2. 在未按下 Enter 送出字詞前按一下 Delete 鍵，預期刪除「冊」字

實際行為：
按下 Delete 後輸入法未刪除「冊」字，而是在冊字後方補入「ㄘ」（註：若輸入ㄌㄨㄛˊ這樣三個注音符號的字，按下 Delete 後補入的則是「ㄌ」），必須連按兩下 Delete 才能刪除此字

預期行為：
按一下 Delete 時直接刪除此「冊」字

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/da65cc785bfb9b57180142e890480559845fbd86 .

Please try it, thanks!

**Comment by zerng07** [comment]
新的修正有以下問題，
重現步驟：
1. 輸入任何字詞，如ㄘㄜˋ（hk4），預期看見候選字為「冊」

實際行為：
輸入 hk4 後候選字消失

預期行為：
輸入 hk4 後可以看見候選字

https://www.dropbox.com/s/fdm9vjhf8k2rjky/ibus-libzhuyin-no-character-commit.webm?dl=0

**Comment by epico** [comment]
Sorry, I can't reproduce it.

Maybe it need another patch in issue #43 .

**Comment by epico** [comment]
Another fix for cursor move.

https://github.com/epico/ibus-libzhuyin/commit/0a050d2be708319c2d52d33e626f3a06aa49f001

**Comment by zerng07** [comment]
還是無法作用。 
我在想這個問題會不是會 issue 38 的 regression（抱歉上次我沒有空幫忙測試 ;P），或是 libzhuyin 併入 libpinyin 造成的呢？

**Comment by epico** [comment]
Okay, I will release new version soon.

Maybe you could try Fedora 27 for testing.

**Comment by epico** [comment]
ibus-libzhuyin 1.8.2 is released.

Please try it, thanks!

**Comment by zerng07** [comment]
Cannot type characters still with 1.8.2.
The problem is the same as https://www.dropbox.com/s/fdm9vjhf8k2rjky/ibus-libzhuyin-no-character-commit.webm?dl=0 shows.

**Comment by epico** [comment]
Please backup and remove the directory ~/.cache/ibus/libzhuyin/,
then log in to see if the bug still exists?

**Comment by zerng07** [comment]
I removed the directory and reboot. It doesn't work.
Here is the result of the screencast video: https://www.dropbox.com/s/pg1fvfych0hpcop/ibus-libzhuyin-1.8.2-%E8%BC%B8%E5%85%A5.webm?dl=0

**Comment by epico** [comment]
I guess you use the git repo for testing?

Could you describe your testing environment?

**Comment by zerng07** [comment]
Yes, I manually built ibus-libzhuyin and libpinyin from git repo.
My testing environment is Fedora 27, x86_64, GNOME 3.26.2.

**Comment by epico** [comment]
Please install libpinyin-devel 2.1.0 and libzhuyin 2.1.0 from Fedora 27 repo.

For ibus-libzhuyin, please use:

./configure --prefix=/usr # if ibus-libzhuyin is installed.

or

make install # after build.

I usually install ibus-libzhuyin from Fedora repo first, then use the first method for testing.

**Comment by zerng07** [comment]
Yeah, I used `./configure --prefix=/usr` and `make install` then rebooted for testing.
Or maybe the problem caused by different preferences?
Here is my preference configuration.
![ibus-libzhuyin-preference](https://user-images.githubusercontent.com/1706450/33985463-a0e08b2e-e0f5-11e7-98ba-48a466633165.png)

**Comment by epico** [comment]
Could you try new Fedora 27 installation with updates-testing repo?
or re-install all libpinyin* and libzhuyin related package?

I built ibus-libzhuyin 1.8.2 for Fedora 27, and currently in updates-testing repo.

**Comment by zerng07** [comment]
I will try it today and report.

**Comment by zerng07** [comment]
I just re-installed a fresh Fedora 27, but ibus-libzhuyin 1.8.2 did not enter the mirror site of updates-testing repo yet. I will report after the update distributes here.

**Comment by FreedomKnight** [comment]
I test it in 1.8.2 and it's work now

**Comment by zerng07** [comment]
I updated the system and found ibus-libzhuyin 1.8.2 updated as well. After testing, the issues solved! 
I'm closing this bug report.
