### ISSUE TITLE
ibus-libzhuyin 1.8.1 移動游標後只能輸入英文

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#43]
ibus-libzhuyin 1.8.1 on fedora 27

重現步驟：

1. 輸入任何字詞，如ㄘㄜˋ（hk4），候選為「冊」
2. 按下左方向鍵，移動游標至冊字前方
3. 按下右方向鍵，移動游標至冊字右方

實際行為：
冊字消失，雖然仍在中文模式下，但此時只能輸出英文，並且無法透過 Shift 鍵再切換回中文

預期行為：
可以正常移動游標並且繼續輸入、刪除文字

**Comment by zerng07** [comment]
移動游標時容易崩潰。
附上 ABRT 的 ureport 連結：https://retrace.fedoraproject.org/faf/reports/1912443/

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/4ddf0fe62b90aa9b9027454d1c32206a561d0bac .

Please try it, thanks!

**Comment by epico** [comment]
ibus-libzhuyin 1.8.2 is released.

Please try it, thanks!

**Comment by zerng07** [comment]
Tested with freshly installed f27 system and updated with ibus-libzhuyin 1.8.2, the problem solved.
Closing the issue.
