### ISSUE TITLE
如果注音符號按錯不能出字，又輸入了聲調符號會導致所有候選字詞消失

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#44]
重現方式：
1. 欲輸入「出來」，注音符號與對應按鍵為「ㄔㄨ ㄌㄞˊ」或「tj x96」
2. 按錯鍵導致輸入為「ㄔㄨ ㄉㄞˊ」即「tj 296」

預期結果：
1. 預期看見「出ㄉㄞˊ」。

實際結果：
1. 「出」的候選字在成字時出現，但ㄉㄞˊ一輸入完，出字隨同後方注音符號一併消失。若此時按下 Delete 鍵一次可刪除「ㄉㄞˊ」，留下出。

目前使用一聲 ( ) 與三聲 (3) 的組合似乎正常。
一併測試會有此情況的聲母+ㄞ韻母+二聲 (6) 的組合，其聲母有：ㄍ (e)、ㄎ (d)、ㄕ (g)、ㄗ (y)、ㄙ (n)
此外，有許多聲母+韻母+輕聲 (7) 的組合，也會有相似問題，數量太多無法一一寫明。

**Comment by epico** [comment]
猜测是由于这些读音没有对应汉字造成的。

**Comment by zerng07** [comment]
確實沒有對應的漢字。至於 ㄈㄞˊ (拼音 fai2)、ㄐㄞˊ (拼音 jai2)、ㄑㄞˊ (拼音 qai2)、ㄒㄞˊ (拼音 xai2)、ㄖㄞˊ (拼音 rai2)、ㄚㄞˊ (aai2)……這些則又可以正常顯示。

**Comment by epico** [comment]
Fixed in https://github.com/epico/libpinyin .

Please try built rpm from http://koji.fedoraproject.org/koji/taskinfo?taskID=23927438 .

**Comment by zerng07** [comment]
目前測試一切正常。
Works fine with the build from koji.

**Comment by zerng07** [comment]
今日發現一個不能正常的顯示的注音拼字：
ㄇㄛ˙ (keyboard: ai7)
一樣有消失不見的問題。

**Comment by epico** [comment]
Fixed in model11.text.tar.gz.

Please try the built rpm from https://koji.fedoraproject.org/koji/taskinfo?taskID=24239213 .

**Comment by zerng07** [comment]
測試正常。已可正常輸入ㄇㄛ˙字，如「饃」。

Works fine with the build.

**Comment by epico** [comment]
As libpinyin 2.1.91 and ibus-libzhuyin 1.8.3 are released, close issue.
