### ISSUE TITLE
Migration request from IBusConfig to GSettings

### ISSUE THREAD

**Issue by fujiwarat** [libzhuyin/ibus-libzhuyin#45]
ibus-libzhuyin uses IBusConfig and I'd ask to migrate it to GSettings and delete IBusConfig.

E.g. setup/main.py
```
from gi.repository import Gio

            self.__config_namespace = 'org.freedesktop.ibus.engine.libzhuyin'
            settings_schema_source =  Gio.SettingsSchemaSource.get_default()
            settings_schema = settings_schema_source.lookup(self.__config_namespace, False)
            keys = settings_schema.list_keys()
            self.__settings = Gio.Settingings(schema=self.__config_namespace)
```

https://groups.google.com/forum/#!topic/ibus-devel/Mu1IoFX-bKE

**Comment by epico** [comment]
Finished code to migrate to use GSettings.

**Comment by fujiwarat** [comment]
Thank you for those implementations.

RF. https://github.com/epico/ibus-libzhuyin/commit/e4978ced9634bc96648d0d8ba052e8fc33ac6516
