### ISSUE TITLE
在候選未送出狀態下，若游標往回走輸入標點會 crash

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#46]
Reproducible: always

Reproduce steps:
1. 切換至 ibus-libzhuyin
2. 輸入兩個字進入候選狀態，但不要按 Enter 送出。例如，輸入ㄐㄧㄥˋㄐㄧㄥˋ (按鍵為：ru/4ru/4)，候選為「靜靜」
3. 讓游標往回走到兩個候選字中央，即「靜|靜」。
4. 按下鍵盤左上角 ` 鍵叫出標點選單，選擇任一標點，例如選單第一項的「…」或第二項的「※」後，按 Enter 送出。

Actual result:
ibus-libzhuyin 崩潰

Expected result:
輸入法可以在兩個候選字之間插入標點，如「靜…靜」

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/5049c5b0ae837cd78314d54db4e22a223c03c6a2 .

**Comment by epico** [comment]
As ibus-libzhuyin 1.8.92 is released, close issue.
