### ISSUE TITLE
候選模式下按空白鍵後，後方字詞無法判斷候選僅維持注音

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#48]
reproducible: always
ibus-libzhuyin version: 1.8.92

Reproduce steps:
1. 切換至 ibus-libzhuyin 模式
2. 輸入任一漢字並按下空白鍵，如 "hk4g4 " 即「測試 」（註：最後有空白）
3. 繼續輸入漢字，例如 "hk4g4" 即「測試」，ibus-libzhuyin 此時顯示為「ㄘㄜˋㄕˋ」，無法判斷空白後的候選字詞
4. 按下 Enter 鍵，則輸出為「測試 ㄘㄜˋㄕˋ」，而非預期的「測試 測試」

Expected result: 測試 測試
Actual result: 測試 ㄘㄜˋㄕˋ

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/4d768fd5f8cb47eca8ad03f45bde9b4acba7da4c .

**Comment by epico** [comment]
As ibus-libzhuyin 1.8.93 is released, close issue.
