### ISSUE TITLE
選字

### ISSUE THREAD

**Issue by lin-shiu** [libzhuyin/ibus-libzhuyin#49]
當選擇非第一個候選字詞時，按下enter理當將底線去除。然而結果為全部候選模式下的字都消失，游標跳至下一行，這時轉為英文輸入法，按shift無法切換中英。
Ubuntu 18.04.1 LTS + IBus 1.5.17 + ibus-libzhuyin1.8.2-1
![screenshot from 2018-10-12 10-01-51](https://user-images.githubusercontent.com/30365651/46843560-0d1e1100-ce06-11e8-8803-3e847fa4fbc4.png)

**Comment by epico** [comment]
请提供所使用的 Linux 发行版，以及 libpinyin 和 ibus-libzhuyin 的版本。

**Comment by lin-shiu** [comment]
Ubuntu 18.04.1 LTS + IBus 1.5.17 + ibus-libzhuyin1.8.2-1
![screenshot from 2018-10-12 10-01-51](https://user-images.githubusercontent.com/30365651/46843537-ee1f7f00-ce05-11e8-8d92-e380449e7a0e.png)

**Comment by epico** [comment]
请开 bug 给 Ubuntu, 升级到 libpinyin 2.2.1 和 ibus-libzhuyin 1.8.92 .

现在 github.com 已经提供了 tar ball 下载。

**Comment by epico** [comment]
As ibus-libzhuyin 1.8.93 is released, close issue.
