### ISSUE TITLE
中文模式下的獨立空白鍵

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#5]
Ibus-libzhuyin 1.7.1

目前中文模式下的空白鍵僅做聲調標音用，無法獨立輸出空白。
例如，"283y4 " (目前輸出爲：ㄉㄚˇㄗˋˉ，打字ˉ)，最後空白鍵所輸出之一聲符號，應直接獨立輸出爲常用的半形空格。由於聲調符號無法作為注音之起頭，這裏應當判斷爲空白。

常用的案例爲中英文間加入空格作美觀性的排版。
例如：中文夾雜 English 時，常會手動補入空格以維持英文單字前後留空的特性。

**Comment by epico** [comment]
Draft fix landed on https://github.com/epico/libzhuyin .

**Comment by epico** [comment]
As libzhuyin 1.0.1 is released, close issue.

Feel free to comment it, if this issue still exists.
