### ISSUE TITLE
Ｈow to use ibus-libzhuyin in pinyin mode?

### ISSUE THREAD

**Issue by marmistrz** [libzhuyin/ibus-libzhuyin#52]
This post claims that ibus-libzhuyin support pinyin input mode but I can't find how to enable it.
https://github.com/libpinyin/libpinyin/issues/96#issuecomment-449795251

**Comment by epico** [comment]
In the "Keyboard" page of setup dialog, change "Keyboard Layout" to "Hanyu Pinyin".

**Comment by marmistrz** [comment]
Thanks!
