### ISSUE TITLE
半形模式下無法以故有方式輸出全形標點

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#54]
reproducible: always
ibus-libzhuyin version: 1.9.0

Reproduce steps:
1. 切換至 ibus-libzhuyin 輸入法，並確認當下處於半形（半角）標點符號模式
2. 依據注音輸入法在半形模式下之故有輸入模式，採 Shift+, 鍵輸出全形逗號，或 Shift+. 輸出全形句號... 等[] 為引號'為頓號
3. 依據注音輸入法故有之全半形快捷鍵 Shift+Space 切換至全形（半角）

Expected result: 2 與 3 步驟應如以往運作
Actual result: 在 1.9.0 中 2 與 3 步驟皆無法作用

情況類同 Issue #31

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/60911931b18008e8daf5eae41bea17447c651105 .

**Comment by epico** [comment]
Could you describe more about the issue?

**Comment by zerng07** [comment]
以下解說故有酷音標點符號輸入方式：
一、Shift+按鍵，如 Shift+,、Shift+:、Shift+'、Shift+.、Shift+/ 四者，可對應輸出，：；？
二、直接按鍵，如 [ ] ' 三者，可依照候選詞頻順序，對應輸出「」、即引號與頓號（此三者符號候選會依詞頻訓練而變動，初始第一順序候選為「」、）
三、上述之 [ ] 二者，可以另搭配 Shfit 按鍵，即 Shift+[、Shift+] 二者，可輸出雙引號『』。 

![鍵盤-圈選](https://user-images.githubusercontent.com/1706450/54836807-f27a8d00-4cff-11e9-9ecc-4300e64058c6.png)

前述第二點，目前在半形模式下，直接按下 [ ] ' 三者，會直接在後選區中輸出為 [ ] ' 而非對應候選符號。請參見我所錄製的影片 https://www.dropbox.com/s/71wo6qkqhinit6u/ibus-libzhuyin-punctuations.webm?dl=0

**Comment by laichiaheng** [comment]
更新到　1.9.0　版本後也出現了此問題。

**Comment by epico** [comment]
Fixed again in https://github.com/epico/ibus-libzhuyin/commit/a9f5f78914d41ad3fecd6ca9d5396c65d2d15a71 .

**Comment by epico** [comment]
计划一两个月之后，发布 ibus-libzhuyin 的新版本，会包含此补丁。

**Comment by epico** [comment]
FYI, ibus-libzhuyin 1.9.1 is released.
