### ISSUE TITLE
Package 'libzhuyin', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by laichiaheng** [libzhuyin/ibus-libzhuyin#55]
在 AUR 建構失敗
從 github 下載 ./configure 也出現同樣的錯誤

**Comment by laichiaheng** [comment]
我安裝了 libpinying 後再用 yay 跑一次就突然好了，詭異

**Comment by epico** [comment]
libzhuyin 项目目前是 libpinyin 和 ibus-libzhuyin 的一部分。
