### ISSUE TITLE
輸入錯誤的拼音不會阻止繼續輸入

### ISSUE THREAD

**Issue by laichiaheng** [libzhuyin/ibus-libzhuyin#57]
譬如：國子ㄩㄒㄢㄗˇ
後半段明顯是無意義的注音組合，但是他不會消掉，導致容易輸入一連串無意義的注音符號，必需要在事後慢慢把它刪掉

**Comment by zerng07** [comment]
為了讓你可以輸入ㄇㄉㄈㄎ，這是本來就刻意設計的特色功能。
Designed as it is. This issue should be closed.
