### ISSUE TITLE
輸入「ㄊㄞˋ」居然有「大」這個字

### ISSUE THREAD

**Issue by laichiaheng** [libzhuyin/ibus-libzhuyin#58]
從字典中查不到「大」有「ㄊㄞˋ」這個發音

**Comment by zerng07** [comment]
發這則 Issue 前請真的查字典確認。https://www.moedict.tw/#%E5%A4%A7
![F0A97E47-9547-4252-8524-30825446B5A6](https://user-images.githubusercontent.com/1706450/56254048-be716c80-60f1-11e9-9f91-f029a5065a48.png)

**Comment by zerng07** [comment]
This issue should be closed.

**Comment by laichiaheng** [comment]
![2019-04-17 18-04-51 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/56279776-55aee200-613b-11e9-8efc-a576297282ec.png)
我之前查教育部的沒看到呀！
