### ISSUE TITLE
英文模式下的標點符號全半狀態

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#6]
ibus-libzuyin 1.7.1
按 Shift 鍵進入英文輸入模式時，由於要輸入英文字句，此時應自動切換為半角符號，以方便使用者輸入半角逗號、句號、破折號、問號等，無需再切換至英文鍵盤。

**Comment by epico** [comment]
我试了下 libchewing，好像也是这样设计的。

还有一个问题，就是如果切换回中文模式，是否应该自动使用全角符号。
目前，还没有一个满意的解决方案。

**Comment by zerng07** [comment]
我不確定 libchewing。

但在 Windows 與 ibus-chewing 下，英文模式都是自動半形符號以便輸入英文字句的，身為長期、重度的智慧型注音使用者，英文模式下專門處理英文是預期的運作方式。

我的建議是，中文模式下使用情境就是要輸入中文，所以應該自動使用全角符號，除非經使用者再手動調整過，否則應該一進入中文模式就是全角符號。英文模式也是同樣道理，使用情境就是要輸入英文，所以應該自動使用半形符號，非經使用者再手動調整過，否則就是半形符號。

**Comment by epico** [comment]
不好意思，我对比了下 ibus-libpinyin，是个 bug.

Draft fix landed on https://github.com/epico/ibus-libzhuyin .

**Comment by epico** [comment]
As ibus-libzhuyin 1.7.2 is released, close issue.

Feel free to comment it, if this issue still exists.
