### ISSUE TITLE
在中文模式下，按下 ESC 無法關閉 Firefox 搜尋列

### ISSUE THREAD

**Issue by laichiaheng** [libzhuyin/ibus-libzhuyin#60]
![2019-04-25 11-28-42 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/56708052-eb56fc80-674d-11e9-85c1-59f9d7f26a6a.png)
必須切換到英數模式才能取消

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/1ec2814cd1df22e742261ed252d6e4f5a645a76f .

**Comment by laichiaheng** [comment]
感謝！期待 1.9.1 版的到來

**Comment by epico** [comment]
libzhuyin 是正式的 repo.
epico 是个人的 repo, 会定期同步到 libzhuyin 的 repo.
