### ISSUE TITLE
中文模式無法使用數字鍵盤的 +-*/ 號

### ISSUE THREAD

**Issue by laichiaheng** [libzhuyin/ibus-libzhuyin#61]
![2019-04-25 18-07-42 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/56728329-1dd01c00-6785-11e9-81c6-f1cb0add1cde.png)
必須要切換回英數模式下才能使用。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libzhuyin/commit/b089823b297b8689b4b2f6e90cdbf8f4bbb1cb92 .
