### ISSUE TITLE
1.9.1 缺少「標點符號」欄位

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#66]
版本：ibus-libzhuyin 1.9.1
重現方式：
1. 按鍵盤左上角 ~ 鍵呼叫出的符號表
2. 符號表中缺少過去 ibus-libzhuyin 補入的「標點符號」項目

參見
https://github.com/libzhuyin/ibus-libzhuyin/blob/master/data/usersymbol.txt
其中第 3 行是過去增補的標點符號。

**Comment by epico** [comment]
我试了试，按 "`" 后，这个功能还是可用的。

**Comment by zerng07** [comment]
是的，不過缺少

`標點符號`=，。？！、；：…・—「」（）《》『』〈〉～＿﹏``

這一行。

**Comment by epico** [comment]
在 Fedora 31 上，標點符號可以使用啊。

能否提供截图呢？

**Comment by zerng07** [comment]
![ibus-libzhuyin-punctuation](https://user-images.githubusercontent.com/1706450/77405293-ea12d180-6ded-11ea-8399-85911bce26ab.png)
作業系統為 Fedora 31。

**Comment by zerng07** [comment]
最近使用又看見了，不確定什麼原因造成。
懷疑當時可能誤將 ibus-libzhuyin 切換為 ibus-chewing 使用，因為 ibus-chewing 中沒有標點符號這一樣。

Close as it works for me.
