### ISSUE TITLE
英文模式下若按下 Delete 後，再切換回中文模式便無法輸入中文

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#7]
ibus-libzhuyin 1.7.1

重現步驟：
1. 按下 Shift 鍵切換至英文模式
2. 輸入幾個英文字母，例如 Englush
3. 按下 Delete 鍵往前刪除錯打的英文字母，本例中按下 3 次，變成 Engl
4. 接下來，無論有無輸入英文字母，只要再按下 Shift 鍵切回中文模式，中文模式下就無法出現注音符號以輸入中文

**Comment by epico** [comment]
Draft fix landed on https://github.com/epico/ibus-libzhuyin .

**Comment by epico** [comment]
As ibus-libzhuyin 1.7.2 is released, close issue.

Feel free to comment it, if this issue still exists.
