### ISSUE TITLE
中文模式下以 Ctrl 為開頭的特殊組合鍵

### ISSUE THREAD

**Issue by zerng07** [libzhuyin/ibus-libzhuyin#8]
常見以 Ctrl 起頭的特殊組合鍵，如 Ctrl+C, Ctrl+V, Ctrl+S, Ctrl+F 等，目前在中文模式下無作用，需切換至英文模式方能作用。

建議支援在中文模式下也能運用 Ctrl 開頭的特殊按鍵組合。

**Comment by epico** [comment]
Draft fix landed on https://github.com/epico/ibus-libzhuyin .

**Comment by epico** [comment]
As ibus-libzhuyin 1.7.2 is released, close issue.

Feel free to comment it, if this issue still exists.
