### ISSUE TITLE
請問可以修復 Wayland 下無法輸入中文的問題嗎？

### ISSUE THREAD

**Issue by laichiaheng** [libzhuyin/ibus-libzhuyin#80]
在 Wayland 下除非使用 Xorg 程式，啟用了 XWayland，否則 ibus-chewing 永遠無法輸入中文。

**Comment by epico** [comment]
这个问题请报告给 https://github.com/chewing/ , 谢谢！

**Comment by laichiaheng** [comment]
@epico 抱歉，看錯地方
