### ISSUE TITLE
預設能否除了空白選字還增加 enter 選字

### ISSUE THREAD

**Issue by FreedomKnight** [libzhuyin/ibus-libzhuyin#9]
如題，空白選字與 enter 選字在新注音之下似乎都有人使用
不知道能否加上這個預設呢？

**Comment by epico** [comment]
不好意思，请详细说明一下，谢谢。

**Comment by zerng07** [comment]
他的意思應該是這樣的：

當我們輸入詞句時，若有需要修改候選字詞，會用左右鍵移動游標到欲修改字詞前方，按下鍵進入候選字詞列表，再利用上下鍵移動選項或 Page Up/Page Down 翻頁，此時若要決定字詞是哪一項，便要按下選擇字詞的鍵，來選定該字詞，目前預設採用空白鍵。

我推測他的建議是，在新注音之下可以讓人手動設定 Enter 鍵選字詞 (大部分注音類輸入法的預設值) 或空白鍵選字詞 (較少見)，是否能加上這個選項給使用者調整做預設呢？

以上翻譯之。:)

**Comment by FreedomKnight** [comment]
我是上面的意思沒錯，真的不好意思，我沒有好好的說明
小弟我真心覺得 libzhuyin 真的很像我們注音輸入法使用者的習慣，只剩下一點東西略有不同

**Comment by epico** [comment]
没关系，谢谢报 issue. :-)

**Comment by epico** [comment]
Draft fix landed on https://github.com/epico/ibus-libzhuyin .

**Comment by zerng07** [comment]
真是太感動了！我好幾年沒看過真的有開發者這麼熱心、積極開發注音輸入法了！

我身為注音輸入法用戶對您表示由衷的感謝！

**Comment by epico** [comment]
不客气。:)

**Comment by epico** [comment]
As ibus-libzhuyin 1.7.2 is released, close issue.

Feel free to comment it, if this issue still exists.
